import { useState } from "react";
import Reveal from "../components/layout/Reveal";
import { useFrontendSettings } from "../hooks/useFrontendSettings";

function Toggle({ label, description, checked, onChange }: { label: string; description: string; checked: boolean; onChange: (checked: boolean) => void }) {
  return <label className="flex cursor-pointer items-start justify-between gap-6 border-b border-line py-5 last:border-b-0"><span><span className="block text-sm text-ink-0">{label}</span><span className="mt-1 block text-sm text-ink-2">{description}</span></span><input type="checkbox" checked={checked} onChange={(event) => onChange(event.target.checked)} className="mt-1 h-5 w-5 shrink-0 accent-crimson" aria-label={label} /></label>;
}

export default function Settings() {
  const { settings, updateSettings, resetSettings } = useFrontendSettings();
  const [resetMessage, setResetMessage] = useState("");
  const reset = () => { resetSettings(); setResetMessage("Preferences reset."); };
  return <div className="px-5 pb-24 pt-28 md:px-10"><div className="mx-auto max-w-[1200px]">
    <Reveal><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="mono-label mb-3">FRONTEND PREFERENCES AND DEMO CONTROLS</p><h1 className="font-display text-5xl tracking-tight sm:text-6xl">SETTINGS</h1></div><span className="border border-line-2 px-3 py-2 font-mono text-[10px] tracking-[0.14em] text-ink-2">LOCAL FRONTEND SETTINGS</span></div></Reveal>
    <Reveal delay={80} className="mt-10 border border-line-2 bg-surface p-5 sm:p-6"><p className="mono-label mb-4">APPEARANCE</p><Toggle label="REDUCE ANIMATIONS" description="Minimize non-essential interface motion." checked={settings.reduceMotion} onChange={(reduceMotion) => updateSettings({ reduceMotion })} /><Toggle label="COMPACT EVENT ROWS" description="Use denser spacing in event-history views." checked={settings.compactEvents} onChange={(compactEvents) => updateSettings({ compactEvents })} /><div className="flex flex-wrap items-center justify-between gap-5 py-5"><span><span className="block text-sm text-ink-0">VISUALIZATION DENSITY</span><span className="mt-1 block text-sm text-ink-2">Adjust spacing in visualization-heavy views.</span></span><div className="flex border border-line-2" role="group" aria-label="Visualization density">{(["standard", "compact"] as const).map((density) => <button type="button" key={density} onClick={() => updateSettings({ visualizationDensity: density })} aria-pressed={settings.visualizationDensity === density} className={`px-4 py-3 font-mono text-[10px] tracking-[0.12em] ${settings.visualizationDensity === density ? "bg-crimson-3/15 text-crimson" : "text-ink-2"}`}>{density.toUpperCase()}</button>)}</div></div></Reveal>
    <Reveal delay={100} className="mt-8 border border-line-2 bg-surface p-5 sm:p-6"><p className="mono-label mb-4">VISUALIZATIONS</p><Toggle label="SHOW WAVEFORM" description="Display waveform cards on supported frontend pages." checked={settings.showWaveform} onChange={(showWaveform) => updateSettings({ showWaveform })} /><Toggle label="SHOW FREQUENCY SPECTRUM" description="Display spectrum cards on supported frontend pages." checked={settings.showSpectrum} onChange={(showSpectrum) => updateSettings({ showSpectrum })} /><Toggle label="SHOW SPECTROGRAM" description="Display spectrogram cards on supported frontend pages." checked={settings.showSpectrogram} onChange={(showSpectrogram) => updateSettings({ showSpectrogram })} /></Reveal>
    <Reveal delay={120} className="mt-8 border border-line-2 bg-surface p-5 sm:p-6"><p className="mono-label mb-4">DEMO MODE</p><Toggle label="SHOW DEMO / SIMULATION LABELS" description="Reduce repeated labels only; key simulation notices remain visible for accuracy." checked={settings.showDemoLabels} onChange={(showDemoLabels) => updateSettings({ showDemoLabels })} /><Toggle label="AUTO-RUN DEMO ANIMATIONS" description="Allow supported local demo sequences to begin automatically when implemented." checked={settings.autoRunDemo} onChange={(autoRunDemo) => updateSettings({ autoRunDemo })} /><div className="flex flex-wrap items-center justify-between gap-4 pt-5"><div><p className="text-sm text-ink-0">RESET DEMO PREFERENCES</p><p className="mt-1 text-sm text-ink-2">Restore the local frontend defaults.</p></div><button type="button" onClick={reset} className="border border-line-2 px-5 py-3 font-mono text-[10px] tracking-[0.12em] text-ink-1 transition-colors hover:border-crimson hover:text-crimson">RESET TO DEFAULTS</button></div>{resetMessage && <p className="mt-4 text-sm text-system" role="status">{resetMessage}</p>}</Reveal>
  </div></div>;
}
